name: Composite Action

description: A composite action to build Laravel applications

runs:
  using: 'composite'
  steps:
    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}

    - name: Checkout php
      uses: actions/checkout@v4

    - name: Setup Env
      run: |
        cp .env.ci .env
        cp .env.ci .env.testing

    - name: Install dependencies
      run: |
        composer install

    - name: Cache the app dependencies
      uses: actions/cache@v4.0.2
      with:
        key: ${{ github.sha }}-php-vendor-cache
        path: ./vendor

    - name: Generate the Key
      run: |
        php artisan key:generate
