name: "Build Reusable Workflow For Laravel app"

on:
  workflow_call:
    inputs:
      php-version:
        required: true
        type: string
jobs:
  build:
    name: Build Laravel App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout php
        uses: actions/checkout@v4

      - uses: Verdent-Sphere-Thiha-Zaw/app/.github/prepare-action@dev
