name: "Reusable Workflow"

on:
  workflow_call:
    inputs:
      php-version:
        required: true
        type: string
    # secrets:
    #   required-secrets:
    #     required: true

jobs:
  build:
    name: Build Laravel App
    runs-on: ubuntu-latest
    steps:
      - name: Run Composite Action
        uses: ./.github/prepare-action
        with:
          php-version: ${{ inputs.php-version }}
