name: "CI Workflow"

on:
    push:
      branches:
        - dev
        - main
    pull_request:
      branches:
        - dev
        - main

jobs:
  build:
    name: Build laravel app
    uses: ./.github/workflows/build.yaml
    with:
      php-version: "8.2"

  test:
    name: Test Laravel App
    needs: [build]
    uses: ./.github/workflows/test.yaml
    with:
      php-version: "8.2"

  push:
    name: Push the Docker Image
    needs: [test]
    uses: ./.github/workflows/docker_push.yaml
    secrets: inherit


