name: "CI Workflow"

on:
    push:
      branches:
        - dev
        - main
    pull_request:
      branches:
        - dev
        - main

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    with:
      php-version: "8.2"

  test:
    name: Test
    needs: [build]
    uses: ./.github/workflows/test.yaml
    with:
      php-version: "8.2"

  push:
    name: Push
    needs: [test]
    uses: ./.github/workflows/push.yaml

# jobs:
#   build_and_push:
#     name: Build and Push Docker Image
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4.1.7

#       - name: Docker Build
#         uses: docker/setup-buildx-action@v3.3.0

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v3.2.0
#         with:
#           registry: https://index.docker.io/v1/
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

    # push:
    #   name: Push
    #   needs: [test]
    #   uses: ./.github/workflows/push.yaml
    #   runs-on: ubuntu-latest
    #   steps:
    #     - name: My Step
    #       uses: ./.github/workflows/push.yaml
    #       with:
    #         uname: ${{ secrets.DOCKERHUB_USERNAME }}
    #         pwd: ${{secrets.DOCKERHUB_TOKEN}}



