name: "CI Workflow"
on:
    push:
    pull_request:
      branches:
        - dev
        - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    with:
      php-version: "8.2"

  test:
    name: Test
    needs: [build]
    uses: ./.github/workflows/test.yaml
    with:
      php-version: "8.2"

  sec:
    name: Sec Check
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Testing with SonarQube
        run:
          echo "Thank you for everything"
    # uses: ./.github/workflows/security.yaml
    # secrets:
    #   - GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   - SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #   - SONAR_PROJECT_KEY: ${{secrets.SONAR_PROJECT_KEY}}
    #   - SONAR_ORGANIZATION: ${{secrets.ORG_key}}

  push:
    name: Push
    needs: [sec]
    uses: ./.github/workflows/push.yaml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}


