name: "Build Reusable Workflow For Laravel app"

on:
  workflow_call:
    inputs:
      dockerhub_username:
        required: true
        type: string
      dockerhub_password:
        required: true
        type: string
    # secrets:
    #   required-secrets:
    #     required: true


jobs:
  build_laravel_app:
    name: Build Laravel App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{inputs.dockerhub_username}}
          password: ${{inputs.dockerhub_password}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{inputs.dockerhub_username}}/laravel-app:latest
