name: "Build Reusable Workflow For Laravel app"

on:
  workflow_call:
    inputs:
      uname:
        required: true
        type: string
      pwd:
        required: true
        type: secret

jobs:
  build_laravel_app:
    name: Build Laravel App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: "${{ input.uname }}"
          password: "${{ input.pwd }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ input.uname }}/laravel-app:latest
