name: "Build Reusable Workflow For Laravel app"

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      password:
        required-secrets:
          required: true

jobs:
  build:
    name: Build Laravel App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout php
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ inputs.username }}
          password: ${{ inputs.password }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ inputs.username }}/laravel-app:latest
