name: "Build Reusable Workflow For Laravel app"

on:
  workflow_call:
    inputs:
      # php-version:
      #   required: true
      #   type: string
      secrets:
        required-secrets:
          required: true

jobs:
  build:
    name: Build Laravel App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout php
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ inputs.secrets.DOCKERHUB_USERNAME }}
          password: ${{ inputs.secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ inputs.secrets.DOCKERHUB_USERNAME }}/laravel-app:latest
