name: Push Docker image with Trivy scan results

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build Docker image
      - name: Build Docker image
        id: build
        run: |
          docker build -t laravel_app:latest .
          docker save laravel_app:latest -o vuln-image.tar

      # Run Trivy vulnerability scanner in tarball mode
      - name: Run Trivy vulnerability scanner
        id: trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          input: vuln-image.tar
          severity: 'CRITICAL,HIGH'

      # Check Trivy scan result
      - name: Check Trivy scan result
        if: steps.trivy.outputs.exit-code != 0
        run: |
          echo "Trivy scan failed with CRITICAL or HIGH vulnerabilities."
          exit 1

      # Commit Trivy scan results to the branch
      - name: Commit Trivy scan results
        if: steps.trivy.outputs.exit-code == 0
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          echo "Trivy scan results:
          $(trivy --format template --template '{{ range .Vulnerabilities }}- {{ . }}\n{{ end }}' --severity HIGH,Critical)" | git commit -a -F -

      # Push changes to GitHub
      - name: Push changes to GitHub
        if: steps.trivy.outputs.exit-code == 0
        run: |
          git push

      # Build and push Docker image if Trivy scan passed
      - name: Build and push Docker image
        if: steps.trivy.outputs.exit-code == 0
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/laravel-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/laravel-app:latest

