name: "Build Reusable Workflow For Laravel app"

on: workflow_call
    # inputs:
    #   username:
    #     required: true
    #     type: string
    #   password:
    #     required: true
    jobs:
      build:
        - name: Checkout php
          uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{inputs.dockerusername}}
            password: ${{inputs.dockerpassword}}

        - name: Build and push Docker image
          uses: docker/build-push-action@v3
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{inputs.dockerusername}}/laravel-app:latest
