# name: "Push Docker Image"
# on:
#   workflow_call:
#     inputs:
#       dockerusername:
#         required: true
#         type: string
#       dockerpassword:
#         required: true
#         type: string
#     # secrets:
#     #   required-secrets:
#     #     required: true

# jobs:
#   build:
#     name: Push Docker Image
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout php
#         uses: actions/checkout@v4

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{inputs.dockerusername}}
#           password: ${{inputs.dockerpassword}}

#       - name: Build and push Docker image
#         uses: docker/build-push-action@v3
#         with:
#           context: .
#           file: ./Dockerfile
#           push: true
#           tags: ${{inputs.dockerusername}}/laravel-app:latest
name: Push Docker image
on: workflow_call

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Docker Build
        uses: docker/setup-buildx-action@v3.3.0


      - name: Log in to Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          registry: https://index.docker.io/v1/
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/laravel-app:latest
