name: Push Docker image

on:
  workflow_call:
    inputs:
      uname:
        required: true
        default: ${{ secrets.DOCKERHUB_USERNAME }}
      pwd:
        required: true
        default: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Docker Build
        uses: docker/setup-buildx-action@v3.3.0

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          registry: https://index.docker.io/v1/
          username: ${{ inputs.uname }}
          password: ${{ inputs.pwd }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ inputs.uname }}/laravel-app:latest
